### ISSUE TITLE
Alignment of Close button on Top left

### ISSUE THREAD

**Issue by itsezc** [widgetbot-io/embed#107]
The alignment of the close button prevents access to specific features of the widget.

As can be seen here **On the top left of the widget**:
![Alignment Issue](https://user-images.githubusercontent.com/33750251/61990392-d2edcb00-b037-11e9-8642-23e364236842.png)

Suggested behavior:
The close button should be on the bottom right of the widget

![Working Example](https://user-images.githubusercontent.com/33750251/61990400-04669680-b038-11e9-8c25-7559c5ac4015.png)

The CSS used to align the button (manually via Inspect Element)
```css
element.style {
    position: absolute;
    top: 545px;
    left: 345px;
}
```
